## import libraries and functions load cleaned data

In [1]:
%load_ext autoreload
%autoreload 2

import sys
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV

sys.path.append("..")
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

from src.extraction import load_processed, save_processed, FEATURES, TARGET

df_clean = load_processed("data_cleand.csv")

df_clean

       carat        cut color clarity  depth  table  price    x    y    z
0       0.23      Ideal     E     SI2  61.50  55.00    326 3.95 3.98 2.43
1       0.21    Premium     E     SI1  59.80  61.00    326 3.89 3.84 2.31
2       0.23       Good     E     VS1  56.90  65.00    327 4.05 4.07 2.31
3       0.29    Premium     I     VS2  62.40  58.00    334 4.20 4.23 2.63
4       0.31       Good     J     SI2  63.30  58.00    335 4.34 4.35 2.75
...      ...        ...   ...     ...    ...    ...    ...  ...  ...  ...
49841   0.72      Ideal     D     SI1  60.80  57.00   2757 5.75 5.76 3.50
49842   0.72       Good     D     SI1  63.10  55.00   2757 5.69 5.75 3.61
49843   0.70  Very Good     D     SI1  62.80  60.00   2757 5.66 5.68 3.56
49844   0.86    Premium     H     SI2  61.00  58.00   2757 6.15 6.12 3.74
49845   0.75      Ideal     D     SI2  62.20  55.00   2757 5.83 5.87 3.64

[49846 rows x 10 columns]

## variables

In [2]:
cat_col = ['cut', 'color', 'clarity']

cut_order = ["Fair","Good","Very Good","Premium","Ideal"]
color_order = ["J","I","H","G","F","E","D"]
clarity_order = ["I1","SI2","SI1","VS2","VS1","VVS2","VVS1","IF"]

num_col = ['carat', 'depth', 'table', 'x', 'y', 'z']

preprocessor = ColumnTransformer(
    transformers=[
        ("cat",OrdinalEncoder(categories=[cut_order, color_order, clarity_order]),cat_col),
        ("num", StandardScaler(),num_col)
    ]  
)

preprocessor

ColumnTransformer(transformers=[('cat',
                                 OrdinalEncoder(categories=[['Fair', 'Good',
                                                             'Very Good',
                                                             'Premium',
                                                             'Ideal'],
                                                            ['J', 'I', 'H', 'G',
                                                             'F', 'E', 'D'],
                                                            ['I1', 'SI2', 'SI1',
                                                             'VS2', 'VS1',
                                                             'VVS2', 'VVS1',
                                                             'IF']]),
                                 ['cut', 'color', 'clarity']),
                                ('num', StandardScaler(),
                                 ['carat', 'depth', 'table', 'x', 'y', 'z'])])

## Train/Test Split

In [3]:
X = df_clean[FEATURES]
y = df_clean[TARGET]

X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X, y

(       carat        cut color clarity    x    y    z  depth  table
 0       0.23      Ideal     E     SI2 3.95 3.98 2.43  61.50  55.00
 1       0.21    Premium     E     SI1 3.89 3.84 2.31  59.80  61.00
 2       0.23       Good     E     VS1 4.05 4.07 2.31  56.90  65.00
 3       0.29    Premium     I     VS2 4.20 4.23 2.63  62.40  58.00
 4       0.31       Good     J     SI2 4.34 4.35 2.75  63.30  58.00
 ...      ...        ...   ...     ...  ...  ...  ...    ...    ...
 49841   0.72      Ideal     D     SI1 5.75 5.76 3.50  60.80  57.00
 49842   0.72       Good     D     SI1 5.69 5.75 3.61  63.10  55.00
 49843   0.70  Very Good     D     SI1 5.66 5.68 3.56  62.80  60.00
 49844   0.86    Premium     H     SI2 6.15 6.12 3.74  61.00  58.00
 49845   0.75      Ideal     D     SI2 5.83 5.87 3.64  62.20  55.00

 [49846 rows x 9 columns],
        price
 0        326
 1        326
 2        327
 3        334
 4        335
 ...      ...
 49841   2757
 49842   2757
 49843   2757
 49844   2757
 49845   2757

 [49846 rows x 1 columns])

## Model Training

In [4]:
models = {
    "Linear Regression" : LinearRegression(),
    "Random Forest": RandomForestRegressor(random_state=42),
}

pipelines = {
    name : Pipeline(steps=[
        ("preprocessing", preprocessor),
        ("regressor", model)
    ]
    )
    for name, model in models.items()
}

In [5]:
results = []

for name, pipeline in pipelines.items():
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    results.append({
        "Model" : name,
        "MAE"   : mean_absolute_error(y_test, y_pred),
        "RMSE"  : mean_squared_error(y_test, y_pred) ** 0.5,
        "R2"    : r2_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results).sort_values(by="RMSE")

display(results_df)

c:\Users\lenovo pc\Desktop\diamond-price-ml\.venv\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

               Model    MAE    RMSE   R2
1      Random Forest 266.78  541.50 0.98
0  Linear Regression 801.83 1214.73 0.91

## Cross-Validation GridSearchCV

In [6]:

param_grid_rf = {
    "regressor__n_estimators": [50, 100, 200],
    "regressor__max_depth": [None, 10, 20],
    "regressor__min_samples_split": [2, 5, 10]
}

param_grid_lr = {
    "regressor__fit_intercept": [True, False]
}

models_param_grid = {
    "Linear Regression": param_grid_lr,
    "Random Forest": param_grid_rf
}


for name, pipeline in pipelines.items():

    if name not in models_param_grid:
        continue
    print(f"\nTraining: {name}")

    grid_search = GridSearchCV(
        estimator=pipeline,
        param_grid=models_param_grid[name],
        cv=5,
        scoring="neg_root_mean_squared_error",
        n_jobs=-1
    )

    grid_search.fit(X_train, y_train)

    print(f"\nModel: {name}")
    print("Best parameters:", grid_search.best_params_)
    print("Best CV RMSE:", -grid_search.best_score_)

Training: Linear Regression

Model: Linear Regression
Best parameters: {'regressor__fit_intercept': True}
Best CV RMSE: 1204.5521378872497

Training: Random Forest

c:\Users\lenovo pc\Desktop\diamond-price-ml\.venv\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Model: Random Forest
Best parameters: {'regressor__max_depth': 20, 'regressor__min_samples_split': 5, 'regressor__n_estimators': 200}
Best CV RMSE: 544.1847213718677